# Generated by Django 2.0.3 on 2018-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180318_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.IntegerField(),
        ),
    ]
