# Generated by Django 2.0.3 on 2018-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180322_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to='media'),
        ),
    ]
