# Generated by Django 2.0.3 on 2018-03-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
    ]
